
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.uploadfile.mtom.service;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-06T15:23:40.405+05:30
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "UploadFile",
                      portName = "UploadServiceSOAPPort",
                      targetNamespace = "http://www.example.org/UploadFile/mtom/service",
                      wsdlLocation = "file:/C:/Users/basanta.kumar.hota/workspace/WebserviceUploadData/src/main/resources/com/wud/wsdl/UploadFile.wsdl",
                      endpointInterface = "org.example.uploadfile.mtom.service.UploadService")
                      
public class UploadServiceSOAPPortImpl implements UploadService {

    private static final Logger LOG = Logger.getLogger(UploadServiceSOAPPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.uploadfile.mtom.service.UploadService#upload(org.example.uploadfile.mtom.types.InputRequest request)*
     */
    public org.example.uploadfile.mtom.types.UploadResponse upload(org.example.uploadfile.mtom.types.InputRequest request) { 
        LOG.info("Executing operation upload");
        System.out.println(request);
        try {
            org.example.uploadfile.mtom.types.UploadResponse _return = new org.example.uploadfile.mtom.types.UploadResponse();
            _return.setResponse("Response1671438052");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
