package org.example.uploadfile.mtom.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-06T15:23:40.416+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.example.org/UploadFile/mtom/service", name = "UploadService")
@XmlSeeAlso({org.example.uploadfile.mtom.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UploadService {

    @WebMethod(action = "http://www.example.org/UploadFile/mtom/service/upload")
    @WebResult(name = "UploadResponse", targetNamespace = "http://www.example.org/UploadFile/mtom/types", partName = "response")
    public org.example.uploadfile.mtom.types.UploadResponse upload(
        @WebParam(partName = "request", name = "InputRequest", targetNamespace = "http://www.example.org/UploadFile/mtom/types")
        org.example.uploadfile.mtom.types.InputRequest request
    );
}
