
package org.example.uploadfile.mtom.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-06T15:23:40.320+05:30
 * Generated source version: 3.1.10
 * 
 */
public final class UploadService_UploadServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/UploadFile/mtom/service", "UploadFile");

    private UploadService_UploadServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UploadFile.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UploadFile ss = new UploadFile(wsdlURL, SERVICE_NAME);
        UploadService port = ss.getUploadServiceSOAPPort();  
        
        {
        System.out.println("Invoking upload...");
        org.example.uploadfile.mtom.types.InputRequest _upload_request = new org.example.uploadfile.mtom.types.InputRequest();
        _upload_request.setFileType("FileType2087764120");
        _upload_request.setFilePath("FilePath720642014");
        javax.activation.DataHandler _upload_requestFile = null;
        _upload_request.setFile(_upload_requestFile);
        org.example.uploadfile.mtom.types.UploadResponse _upload__return = port.upload(_upload_request);
        System.out.println("upload.result=" + _upload__return);


        }

        System.exit(0);
    }

}
